services:
  server-monitoring:
    build:
      context: ./server-monitoring
      dockerfile: Dockerfile
    container_name: server-monitoring
    ports:
      - "8081:8081"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./cert:/etc/caddy/certs:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - server-monitoring
    restart: unless-stopped

volumes:
  frontend_build:
  caddy_data:
  caddy_config:
